name: bayesian_traffic

dependencies:
    - python==3.7.3
    - pip:
        - gym==0.17.0
        - pytz
        - scipy==1.1.0
        - lxml==4.2.4
        - six
        - path.py
        - python-dateutil==2.7.3
        - tensorflow==2.0.0
        - cloudpickle==1.2.1
        - setuptools==41.0.0
        - numpy==1.18.4
        - pyprind==2.11.2
        - nose2==0.8.0
        - cached_property
        - joblib==0.10.3
        - matplotlib==3.0.0
        - dill
        - lz4
        - ray==0.8.4
        - setproctitle
        - psutil
        - opencv-python
        - boto3==1.4.8
        - redis~=2.10.6
        - tabulate
